config/routes.rb
Disc_orders::Application.routes.draw do
  root to: 'orders#recent'
  resources :orders
  get '/total', action: 'total', controller: 'orders'
  get '/index', action: 'index', controller: 'orders'
  post '/index', action: 'index', controller: 'orders'
  match '/search', to: 'orders#search'

  resources :users, only: [:new, :create, :index, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: ['get', 'delete']

  resources :sessions, only: [:new, :create, :destroy]

  match '/data', to: 'orders#data'
  

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  bunk       :string(255)
#  white      :integer
#  orange     :integer
#  blue       :integer
#  paid       :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  received   :boolean          default(FALSE)
#  user_id    :integer
#

class Order < ActiveRecord::Base
  belongs_to :user

  attr_accessible :name, :bunk, :white, :orange, :blue, :paid, :received, :price
  before_validation {self.name = name.titleize; self.bunk=bunk.capitalize}
  before_validation {match_data = /([A,a,B,b])(\d{1,2})/.match self.bunk
              if match_data
                self.bunk = "#{match_data[1].capitalize}-#{match_data[2]}"
              end
              }
  
  def total
  	self.blue+self.white+self.orange
  end

  def price
  	self.total*8
  end

  validates :name, :bunk, presence: true
  validates :name, uniqueness: {scope: [:user_id, :bunk]}
  validate :ordered_discs
  validate :paid_before_received

  def ordered_discs
  	if self.total <= 0
  		errors[:base]<<"No discs ordered"
  	end
  end

  def paid_before_received
    if not self.paid and self.received
      errors.add :received, "before paid."
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    if not params[:id_array].nil?
      id_array = params[:id_array].split(",").map { |i| i.to_i}
      @orders = id_array.map { |id| Order.find(id)  }
    else
      @orders = all_orders
    end
    @orders.sort_by! {|x| x.created_at }.reverse!
    #@orders = @orders.paginate(page: params[:page], per_page: 10)
    #gon.orders = @orders

    redirect_to @orders[0] if @orders.size == 1
  end

  def recent
    @orders = signed_in? ? current_user.orders : Order.where('user_id'=>nil)
    @orders = @orders.paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = signed_in? ? current_user.orders.new(params[:order]) : Order.new(params[:order])
    if @order.save
      flash[:info] = "Order placed for #{@order.name} in bunk #{@order.bunk} for #{@order.white} white, #{@order.orange} orange, and #{@order.blue} blue frisbees."
      if @order.paid
        flash[:success] = "#{@order.name} paid $#{@order.price}."
      else
        flash[:danger] = "Remeber to bring $#{@order.price} when you pick up your discs."
      end
      redirect_to root_path
    else
      render 'new'
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        message = case @order.received
          when true then {received: "#{@order.name} in bunk #{@order.bunk} has received his/her #{@order.white} white, #{@order.orange} orange, and #{@order.blue} blue frisbees."}
          when false then {notreceived: "#{@order.name} in bunk #{@order.bunk} has NOT received his/her #{@order.white} white, #{@order.orange} orange, and #{@order.blue} blue frisbees."}
          end
        format.html {
          if request.referer =~ /edit/
            redirect_to @order, notice: 'Order was successfully updated.'
          elsif request.referer =~ /index/
            redirect_to root_path, notice: 'Order was successfully updated.'
          else
            redirect_to request.referer, notice: 'Order was successfully updated.'
          end
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def total
    @order_total = all_orders.size
    
    #white_total = blue_total = orange_total = []
    [:white, :orange, :blue].each do |color|
      instance_variable_set("@#{color}_count", [])
      all_orders.each {|order| instance_variable_get("@#{color}_count").append(order[color]) if order[color].is_a? Fixnum}
      instance_variable_set("@#{color}_total", instance_variable_get("@#{color}_count").sum)
    end
    @disc_total=@white_total+@blue_total+@orange_total
    @received_total=@price_total=0
    all_orders.each {|order| @received_total+=1 if order.received}
    all_orders.each {|order| @price_total+=order.price}
  end

  def data
    orders = all_orders
    data = orders.collect do |order|
      {name: order.name,
        bunk: order.bunk,
        id: order.id,
        white: order.white,
        orange: order.orange,
        blue: order.blue,
        paid: order.paid,
        price: order.price,
        received: order.received
      }
      end
    data.uniq!
    respond_to {|format| 
      format.html { redirect_to '/404.html'}
      format.json {render json: data}}
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
    def pretty(order)
        order.name = order.name.titleize
        order.bunk=order.bunk.capitalize
        match_data = /([A,a,B,b])(\d{1,2})/.match order.bunk
        if match_data
            order.bunk = "#{match_data[1].capitalize}-#{match_data[2]}"
        end
    end

end

app/views/orders/_form.html.haml
= javascript_include_tag "application"
= form_for(@order, :html => {class: "form-horizontal", role: 'form', id:"order_form"}) do |f|
  = render 'shared/error_messages'
  - cols_input = 4
  - cols_label = 1
  - 
  .form-group
    = f.label :name, "Name", class: "col-sm-#{cols_label}"
    %div{class: "col-sm-#{cols_input}"}
      = f.text_field :name, {placeholder: '', class: "form-control"}
  .form-group
    = f.label :bunk, "Bunk", class: "col-sm-#{cols_label}"
    %div{class: "col-sm-#{cols_input}"}
      = f.text_field :bunk, {placeholder: '', class: "form-control" }
  .form-group
    - @order.white ||= 0
    - @order.orange ||= 0
    - @order.blue ||= 0
    = f.label :white, "Discs", class: "col-sm-#{cols_label}"
    %div{class: "col-sm-#{cols_input}"}
      .input-group
        .input-group-addon White:
        = f.number_field :white, {value: @order.white, min: 0, step: 1, class: "form-control"}
  .form-group
    %div{class: "col-sm-#{cols_input} col-sm-offset-#{cols_label}"}
      .input-group
        .input-group-addon Orange:
        = f.number_field :orange, {value: @order.orange, min: 0, step: 1, class: "form-control"}
  .form-group
    %div{class: "col-sm-#{cols_input} col-sm-offset-#{cols_label}"}
      .input-group
        .input-group-addon Blue:
        = f.number_field :blue, {value: @order.blue, min: 0, step: 1, class: "form-control"}
  .form-group
    - paid_cache = @order.paid.nil? || @order.paid
    = f.label :paid, class: "col-sm-#{cols_label}"
    %div#checkbox_button{class: "col-sm-#{cols_input}"}
      =#%button.btn.form-control{class: "btn-#{paid_cache ? 'success' : 'danger'}"}Paid
      = f.check_box :paid, value: paid_cache
      = f.label :paid, "($#{@order.price})", class: "form-control"
  .form-group
    = submit_tag("Save changes", {:class => "btn btn-primary"})
    = link_to "Back", root_path, class: "btn"
= javascript_include_tag "orders"

app/views/orders/edit.html.erb
<% provide(:title, 'Edit Order') %>
<h1>Editing order</h1>

<%= render 'form' %>

app/views/orders/index.html.haml
%h1 All Orders
%table.table.table-border.table-hover
  %tr
    %th
      %a#name.sort{:href => '#', :'data-no-turbolink'=> ''}Name
    %th
      %a#bunk.sort{:href => '#', :'data-no-turbolink'=> ''}Bunk
    %th White
    %th Orange
    %th Blue
    %th
      %a#paid.sort{:href => '#', :'data-no-turbolink'=> ''}Paid/Due
    %th
      %a#received.sort{:href => '#', :'data-no-turbolink'=> ''}Received
    %th
  - @orders.each do |order|
    %tr
      %td= order.name
      %td= order.bunk
      %td= order.white
      %td= order.orange
      %td= order.blue
      %td#paid
        = form_for order do |f|
          = f.hidden_field :paid, value: !order.paid
          = f.submit "$"+order.price.to_s, class: "btn btn-" + (order.paid ? "success" : "danger"), index: true
      %td#received
        = form_for order do |f|
          = f.hidden_field :received, value: !order.received
          = f.submit (order.received ?  "Yes" : 'No'), class: "btn btn-" + (order.received ? "success" : "danger") +  (!order.paid ? " disabled" : ""), index: true
      %td
        .btn-group
          = link_to(order, class: "btn btn-primary") do
            %span.glyphicon.glyphicon-user
            View
          %a.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to(edit_order_path(order)) do
                %span.glyphicon.glyphicon-pencil
                Edit
            %li
              = link_to(order, method: :delete, data: { confirm: 'Are you sure?' }) do
                %span.glyphicon.glyphicon-trash
                Delete
= link_to "New Order", new_order_path, class: "btn btn-primary"
= javascript_include_tag "table"

app/views/orders/new.html.erb
<% provide(:title, 'New Order') %>
<h1>New order</h1>

<%= render 'form' %>

app/views/orders/recent.html.haml
%h1 Recent Orders
%table.table.table-border.table-hover
  %tr
    %th Name
    %th Bunk
    %th White
    %th Orange
    %th Blue
    %th Paid/Due
    %th Received
    %th
  - @orders.each do |order|
    %tr
      %td= order.name
      %td= order.bunk
      %td= order.white
      %td= order.orange
      %td= order.blue
      %td#paid
        = form_for order do |f|
          = f.hidden_field :paid, value: !order.paid
          = f.submit "$"+order.price.to_s, class: "btn btn-" + (order.paid ? "success" : "danger"), index: true
      %td#received
        = form_for order do |f|
          = f.hidden_field :received, value: !order.received
          = f.submit (order.received ?  "Yes" : 'No'), class: "btn btn-" + (order.received ? "success" : "danger") +  (!order.paid ? " disabled" : ""), index: true
      %td
        .btn-group
          = link_to(order, class: "btn btn-primary") do
            %span.glyphicon.glyphicon-user
            View
          %a.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to(edit_order_path(order)) do
                %span.glyphicon.glyphicon-pencil
                Edit
            %li
              = link_to(order, method: :delete, data: { confirm: 'Are you sure?' }) do
                %span.glyphicon.glyphicon-trash
                Delete
%div.center
  = will_paginate @orders
= link_to "New Order", new_order_path, class: "btn btn-primary"
= javascript_include_tag "table"

app/views/orders/search.html.erb
<% provide(:title, 'Search') %>
<h1>Find An Order</h1>

<dl>
<%= form_tag("/index", :method => "post", class: "form-horizontal", id: 'search_form') do %>
<div class="control-group">
  <dt><%= label_tag(:search, "Name:", class: "control-label") %></dt>
	<div class="controls">
  <dd><%= text_field_tag(:search, nil, class: "search-query") %></dd>
	</div>
</div>

<div class="control-group">
  <input id="id_array" name="id_array" type="hidden">
  <%= submit_tag("Search", {:class => "btn btn-primary"}) %>
  <%= link_to "Back", root_path, class: "btn"%>
  	</div>
</div>
<% end %>
</dl>

<script>
var discs = new Bloodhound({
  datumTokenizer: function (data) {return data.name.split(' ').concat( data.bunk.split("-")[1]).concat(data.bunk).concat(data.bunk.split("-").join(''))},
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch: {url:"../data.json", ttl: 1}
});

discs.initialize()

$('.search-query').typeahead({
  // `ttAdapter` wraps the suggestion engine in an adapter that
  // is compatible with the typeahead jQuery plugin
  hint: true,
  highlight: true},
  {
    source: discs.ttAdapter(),
    displayKey: 'name',
    templates: {
      empty: "<i>No matches</i>",
      suggestion: function (suggestion) {
        return "<p><b>" + suggestion.name + "</b> - <small>" + suggestion.bunk + "</small></p>"
      }
    }
});

search = function (query) {
  output = []
  discs.ttAdapter()(query, function (suggestions) {  
    jQuery.each(suggestions, function (index, item) {
      output.push(item);
    });
  });
  return output
}

$("#search_form").submit(function () {
  query = $("input.search-query.tt-input").val()
  id_array = search(query).map(function (i){return i.id})
  $("#id_array").val(id_array)
})

</script>

app/views/orders/show.html.haml
- provide(:title, 'View Order')
%p#notice= notice
%dl.dl-horizontal
  %dt Name:
  %dd= @order.name

  %dt Bunk:
  %dd= @order.bunk

  %dt White:
  %dd= @order.white

  %dt Orange:
  %dd= @order.orange

  %dt Blue:
  %dd= @order.blue

  %dt Paid:
  %dd
    = form_for @order do |f| 
      = f.hidden_field :paid, value: !@order.paid
      = f.submit "$"+@order.price.to_s, class: "btn btn-" + (@order.paid ? "success" : "danger")
  %dt Received:
  %dd
    = form_for @order do |f|
      = f.hidden_field :received, value: !@order.received
      = f.submit (@order.received ?  "Already Received" : "Not Received"), class: "btn btn-" + (@order.received ? "success" : "danger") +  (!@order.paid ? " disabled" : "")
  %dd
    = link_to 'Edit', edit_order_path(@order), class: "btn btn-info"
    = link_to 'Back', root_path, class: "btn btn-info"

app/views/orders/total.html.erb
<% provide(:title, 'Totals') %>
  <h1>Totals</h1>

<dl class="dl-horizontal">
  <dt>Orders:</dt>
  <dd><%= @order_total %></dd>
  <dt>Discs:</dt>
  <dd><%= @disc_total %></dd>
  <dt>Whites:</dt>
  <dd><%= @white_total %></dd>
  <dt>Oranges:</dt>
  <dd><%= @orange_total %></dd>
  <dt>Blues:</dt>
  <dd><%= @blue_total %></dd>
  <dt>Profits:</dt>
  <dd><%= "$#{@price_total}" %></dd>
  <dt>Served:</dt>
  <dd><%= @received_total %></dd>
</dl>