config/routes.rb
Disc_orders::Application.routes.draw do
  root to: 'orders#recent'
  resources :orders
  get '/total', action: 'total', controller: 'orders'
  get '/index', action: 'index', controller: 'orders'
  post '/index', action: 'index', controller: 'orders'
  match '/search', to: 'orders#search'

  resources :users, only: [:new, :create, :index, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: ['get', 'delete']

  resources :sessions, only: [:new, :create, :destroy]

  match '/data', to: 'orders#data'
  

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to "Disc Orders", root_path, id: "logo", class:"navbar-brand"
  / Collect the nav links, forms, and other content for toggling
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    /%form.navbar-form.navbar-right{role: "search"}
    = form_tag("/index", :method => "post", class: "form-horizontal navbar-form navbar-right", id: 'search_form') do
      .form-group
        .input-group
          = text_field_tag(:name, nil, class: "form-control", id: "menu-search", placeholder: "Search")
          /%button.btn.btn-default.input-group-addon{type: "submit"}
          = button_tag(:class => "btn btn-default input-group-addon", type: 'submit') do
            %span.glyphicon.glyphicon-search
        %input#id_array{name: "id_array", type:"hidden"}
        = javascript_include_tag "search.js"
    %ul.nav.navbar-nav.navbar-right
      %li{class: "#{params[:action] == 'index' and params[:controller] == 'orders' ? 'active' : ''}"}= link_to "All Orders", index_path
      %li{class: "#{params[:action] == 'new'  and params[:controller] == 'orders' ? 'active' : ''}"}= link_to "New Order", new_order_path
      %li{class: "#{params[:action] == 'total'  and params[:controller] == 'orders' ? 'active' : ''}"}= link_to "Totals", action:'total', controller: 'orders'
      - if signed_in?
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            = current_user.name
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to "Sign out", signout_path, method: "delete"
            - if current_user.admin?
              %li= link_to "All Users", users_path
      - else
        / not signed in
        %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    = include_gon
    %title= full_title(yield(:title))
    / Latest compiled and minified CSS
    %link{href: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", rel: "stylesheet"}/
    = stylesheet_link_tag    "application", media: "all"
    %script{:src => "//code.jquery.com/jquery-2.0.3.min.js"}
    = javascript_include_tag "rails"
    = javascript_include_tag "typeahead.bundle"
    = javascript_include_tag "application"
    = csrf_meta_tags
    / Latest compiled and minified JavaScript
    %script{src: "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"}
    :javascript
      var root_url = "#{root_url}"
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}") unless key == :notice
      - if notice
        .alert.alert-info= notice
      %div
        = yield
        = debug(params) if Rails.env.development?
      